// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "amplify",
            "endpoint": "https://3bn0p7c4f5.execute-api.us-east-1.amazonaws.com/react",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "my-website-20190218160601-hostingbucket-react",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://my-website-20190218160601-hostingbucket-react.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
